In [45]:
from sklearn.datasets import load_digits
import pylab as pl
import sklearn.metrics as metrics
import numpy as np


Esta función se le ingresa la lista de digitos y el valor que  quiero tener de digitos y me devuelve una lista con esos value

In [46]:
def filterValue(digits, value):
    filteredList=[]
    for i in range(0, len(digits.target)):
        if digits.target[i]==value:
            filteredList.append(digits.images[i])
    return filteredList



Vamos a verificar la columna de negros

In [47]:
def verifyBlackCol(digit,colIndex):
    isBlack=False
    blackAmount=0
    for i in range(0,8):
        if(digit[i][colIndex]<=3):
            blackAmount+=1
    if blackAmount==8:
        isBlack=True
    return isBlack

Vamos a verificar la segunda columna

In [48]:
def verifySecondCol(digit):
    flag=True
    for i in range(0,8):
        if(digit[i][1]>10):
            flag=False
    return flag
        

In [ ]:
def verifyThirdCol(digit):
    counter=0
    flag=False
    if(digit[0][2]<10):
        counter+=1
    if(digit[1][2]>=8 and digit[1][2]<=16):
        counter+=1
    if(digit[2][2]<=10):
        counter+=1
    if(digit[3][2]<11):
        counter+=1
    if(digit[4][2]>=8):
        counter+=1
    if(digit[5][2]<=13):
        counter+=1
    if(digit[6][2]<=10):
        counter+=1
    if(digit[7][2]<=13):
        counter+=1
    if(counter>=6):
        flag=True
    return flag

In [49]:
def getCol(matrix,col):
    colList=[]
    for i in range(0,8):
        colList.append(matrix[i][col])
    return colList

In [52]:
#listNumbersWanted
digits=load_digits()
listWanted=filterValue(digits, 7)
#print(listWanted[0:3])
pl.gray()

for i in range(0, 20):
    #pl.matshow(listWanted[i])
    print(np.asarray(getCol(listWanted[i],2)))



[ 7.  7.  0.  8. 11.  0.  9. 13.]
[ 1. 13. 10.  3. 16.  8.  0.  0.]
[ 0.  0.  0.  8. 16.  0.  0.  0.]
[ 0.  4.  0.  9. 16.  0.  0.  0.]
[ 9. 14.  0.  8. 16.  2.  8. 13.]
[ 3. 10.  0. 11. 16.  4.  0.  4.]
[ 6. 16.  5.  0. 15. 13.  0.  4.]
[ 3. 13.  1.  9. 16.  4.  2.  4.]
[ 2. 14.  2.  0. 16.  5.  0.  0.]
[ 3. 14. 10.  0.  8.  6.  0.  5.]
[ 2. 12.  2.  0. 16.  6.  0.  0.]
[ 3. 15.  8.  4. 16.  8.  1.  3.]
[ 9. 15.  2.  2. 13. 13.  6. 11.]
[ 2.  8.  0.  0.  4. 11.  1.  4.]
[ 3. 13.  4.  0.  7. 12.  0.  4.]
[10. 14.  1.  2. 16. 10.  6. 13.]
[ 7.  8.  0.  4. 16.  3.  0.  7.]
[ 1. 14.  6.  0.  2.  3.  0.  1.]
[ 5.  4.  0.  2. 13.  3.  0.  6.]
[15.  8.  0.  7. 16.  5.  9. 16.]


<Figure size 432x288 with 0 Axes>